### ISSUE TITLE
Incorrect new URL in 'Should' wiki page

### ISSUE THREAD

**Issue by Atreidae** [pester/docs#115]
The Pester [Github Repo Wiki ](https://github.com/pester/Pester/wiki/Should)page for the Should assertion presently points to https://pester.dev/docs/usage/assertions which leads to a 404.

This link is no longer valid, it should (haha) instead, point to https://pester.dev/docs/assertions/should-command

**Comment by bravo-kernel** [comment]
Thank you, page has been changed. Good catch 👍
