### ISSUE TITLE
Cannot follow / test examples without Get-Emoji.ps1

### ISSUE THREAD

**Issue by robinmalik** [pester/docs#140]
## Location
https://pester-docs.netlify.app/docs/usage/data-driven-tests

- Pester version: 5.2.2

## General summary of the issue

I'm trying to take a working copy of code (e.g. code from the documentation) and run this locally to test and tweak to help me understand how the data driven aspects of Pester behave (sometimes long documentation is harder to understand than getting hands on with things). Without Get-Emoji.ps1 it's not possible to run any of this because the function doesn't exist (obviously!). Please could this file be added to the documentation to download so we can import it? Thank you.

**Comment by nohwnd** [comment]
Moved. I searched my computer but don't have that function.  I hope there is one that can fit all the test examples.

**Comment by nohwnd** [comment]
Looks like there are different requirements in those tests, I guess the best option is to stub out different versions of the function and paste them in the docs, maybe in a collapsible block? If we can control it, I would prefer that the first such block is expanded, and the rest of the blocks are closed - this way the reader is able to notice that the function implementation is there in a collapsible block, and can expand the rest if they want. it's a nice balance between not noticing the implementation, and polluting the whole article with the implementations.

**Comment by asears** [comment]
Giraffe and apple are missing, but here's an older Emojis example. 😊

https://www.powershellgallery.com/packages/Emojis/0.1
