### ISSUE TITLE
Need documentation on $PesterBoundParameters and forwarding strategy

### ISSUE THREAD

**Issue by jazzdelightsme** [pester/docs#158]
I spent a lot of time trying to figure out how to do something pretty simple:

```powershell
        Mock Copy-Item {
            $originalCopyItem = Get-Command Copy-Item -CommandType Cmdlet
            & $originalCopyItem @PesterBoundParameters
        }
```

There are actually two things here that I think should be documented:

1. How to mock something, but still call the original something from within the mock; and
2. How to generically forward parameters to that original thing (`@PesterBoundParameters`).

While not needed for most mocks, this is a valuable technique, and deserves to be mentioned somewhere.

**Comment by fflaten** [comment]
Thanks for the issue. 

You're not really faking (mocking) the function anymore, but rather creating a proxy function.

I agree this could be easier to find though. I'm just not sure if this belongs as an example [here](https://pester.dev/docs/usage/mocking#example) or simply as a Q&A discussion in pester-repo or blog post promoted [here](https://pester.dev/docs/additional-resources/articles) as an edge case.

**Comment by jazzdelightsme** [comment]
IMO, of those two places, I would say that the mocking page example is the better place. Because `$PesterBoundParameters` is a bona fide Pester feature, so I wouldn't expect to only be able to learn about it from a link to a blog somewhere. And maybe also on the reference page for the `Mock` command (mentioned as a special variable available to the script block passed via the `-MockWith` parameter).

**Comment by fflaten** [comment]
Sorry for not being precise. I was thinking about the first part only.

`$PesterBoundParameters` was new in 5.2.0 and should definitely be mentioned in multiple places as [intended](https://github.com/pester/Pester/issues/1542#issuecomment-814954369). 👍
