### ISSUE TITLE
Missing an argument for parameter 'InFile'

### ISSUE THREAD

**Issue by PingPongSet** [pester/docs#159]
I am getting the error below pointed to `  function GetHTTPHeader ($url) `

>  ParameterBindingException: Missing an argument for parameter 'InFile'. Specify a parameter of type 'System.String' and try again.

https://pester.dev/docs/usage/mocking#mocking-a-native-application 
```
Describe 'Mocking native commands' {
    It "Mock bash" {
        function GetHTTPHeader ($url) {
            & curl --url $url `
            -I
        }

        Mock curl { Write-Warning "$args" }

        GetHTTPHeader -url "https://google.com"

        Should -Invoke -CommandName "curl" -Exactly -Times 1 -ParameterFilter { $args[0] -eq '--url' -and $args[1] -eq 'https://google.com'}

        # By converting args to string (will concat using space by default) you can match a pattern if order might change. remember linebreaks
        Should -Invoke -CommandName "curl" -Exactly -Times 1 -ParameterFilter { "$args" -match "--url https://google.com -I" }
    }
}

```

How can I fix this?

Pester version: 5.3.1

**Comment by fflaten** [comment]
Sorry for the late response. I can't reproduce this.
The sample above without modifications works fine for me in 5.3.1 and newer.
