### ISSUE TITLE
Enabling "-Output Detailed" when clicking Run button in Visual Studio Code

### ISSUE THREAD

**Issue by PingPongSet** [pester/docs#160]
Is it possible to enable the command equivalent of "-Output Detailed" when clicking Run button in Visual Studio Code?

For example, the screenshot below, when clicking the `Run` button, it doesn't display each TestCase. 

I want the result of running `Invoke-Pester -Output Detailed .\1.Tests.ps1`
![image](https://user-images.githubusercontent.com/2021414/149322515-3e4d835a-c5f9-4187-9be2-02321dfbfb7c.png)

Any idea?

**Comment by nohwnd** [comment]
There is "magical" variable $PesterPreference, that is used as the default. If you set that in your session it will take the options from there, and merge them with other options that you provide later. You can use your $Profile to set that variable, or just set it in the console manually. 

```powershell
 $PesterPreference = [PesterConfiguration]@{ Output = @{ Verbosity = "Detailed" }}
Invoke-Pester -Configuration @{ Run = @{ ScriptBlock = { Describe "a" { It "b" { "ok" } } } } }

Pester v5.3.0

Starting discovery in 1 files.
Discovery found 1 tests in 11ms.
Running tests.
Describing a
  [+] b 3ms (2ms|1ms)
Tests completed in 46ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```
