### ISSUE TITLE
BeforeDiscovery

### ISSUE THREAD

**Issue by sHooPmyWooP** [pester/docs#173]
Please add BeforeDiscovery to the listing "Put all your code into It, BeforeAll, BeforeEach, AfterAll or AfterEach." on this page: https://pester-docs.netlify.app/docs/migrations/v4-to-v5

**Comment by bravo-kernel** [comment]
Feel free to PR.

**Comment by fflaten** [comment]
Thanks for the input.

> Put no code directly into Describe, Context or on the top of your file, without wrapping it in one of these blocks, unless you have a good reason to do so.

Using BeforeDiscovery is only a way to acknowledge that the wrapped code has a "good reason" to be placed outside the other blocks. It effectively runs the same, during Discovery.

BeforeDiscovery didn't exist in early v5 versions when this guide was written. Should probably rephrase some of the text in that intro and the same at https://pester-docs.netlify.app/docs/usage/discovery-and-run to describe it better.
