### ISSUE TITLE
Search engines show netlify URL

### ISSUE THREAD

**Issue by fflaten** [pester/docs#191]
Google etc. show the netlify URL and not pester.dev when returning a docs-page as results.
Looks like pester.dev is mostly used for the main page.

![image](https://user-images.githubusercontent.com/3436158/172238876-32ac891c-d840-41bf-8168-adece5acc491.png)

![image](https://user-images.githubusercontent.com/3436158/172238916-26cd2bf0-8344-4f67-8aff-e63aefe28b3b.png)

**Comment by fflaten** [comment]
See this answer. Looks like we need a _headers file to fix it for `https://pester-docs.netlify.app/*`.
https://answers.netlify.com/t/prevent-google-from-indexing-netlify-url/18765/2

PR deploys already set to  X-Robots-Tag header, but prod deploy doesn't.

Is this something we add here in repo or is it set in netlify console?

**Comment by fflaten** [comment]
The canonical links in html header also use netlify domain which might be the reason it's preferred for the subpages. Because of this?
https://github.com/pester/docs/blob/0928828ef08f2f135d00973f24ed1f04b7a7ea2e/docusaurus.config.js#L8

**Comment by fflaten** [comment]
> just update whatever is inside `website` and PR it. We can use the preview to analyse the outcome.

`Website`? Where would I place something to be in root of publish directory? The previews already have mandatory noindex robots-header so can't verify it without merge.

**Comment by bravo-kernel** [comment]
My suggestion was basically: make any changes you like, then check the **local website** to see if things match your expectations. If they do, submit the PR to generate the preview.

No offense, you already know but to run the website locally:

```
git clone git@github.com:pester/docs.git
cd docs
yarn install
yarn dev
```

**Comment by fflaten** [comment]
None taken 🙂

Never looked through the build output when running it locally. Also, wasn't sure if there were any additional deployment scripts moving files etc in netlify.

Will submit a PR.
