### ISSUE TITLE
Dark navigation-text in hamburger menu (mobile) while in light mode

### ISSUE THREAD

**Issue by fflaten** [pester/docs#222]
Arrows and "back to main menu" use light color in dark-mode, but dark/black text for some reason in light mode. The light mode feels out of place and is harder to read.

Dark mode (ok):
![image](https://user-images.githubusercontent.com/3436158/182482096-9b50c355-9ba9-49c4-9b1d-7fd190831946.png)

Light mode (not great):
![image](https://user-images.githubusercontent.com/3436158/182482154-840c2c49-8775-40fb-bff6-7cd811dc5d84.png)

Maybe the colors got mixed? Both background-highlight + text-color should have been in the opposite mode? Or current dark mode-style for both?

**Comment by fflaten** [comment]
The X (close sidebar) should also be lighter in light mode.

**Comment by fflaten** [comment]
Also the sun-icon in light mode on desktop.
Should be light when not hovering (then the white circle appears, so icon has to be dark).
![image](https://user-images.githubusercontent.com/3436158/182485472-4268df77-1958-4374-8953-61c5acd03ac9.png)
Again, in dark mode the moon is white when not hovering. Feels like something got mixed up.
![image](https://user-images.githubusercontent.com/3436158/182485692-46d47c30-38f4-495d-9c31-3416a70de9ac.png)

**Comment by bravo-kernel** [comment]
Are these issues also present in the 2.0.x version? They look like "relatively" easy CSS fixes.

**Comment by fflaten** [comment]
Haven't tested yet or looked at theme source. Assuming it's just some css-variables reused too many or in the wrong places :)

**Comment by bravo-kernel** [comment]
IMO anything that improves the look of the theme could instantly be submitted as a PR. If the preview looks better we will merge it.

- We use a [CSS theme override file](https://github.com/pester/docs/blob/master/src/css/custom.css) but you can see that those changes were done a very long time ago
- I am unsure if this is related but I recall some Docusaurus [release notes mentioning breaking changes](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-beta.22)


Perhaps best to first update to 2.0, then take it from there using this as a guideline: https://docusaurus.io/docs/styling-layout#global-styles
