### ISSUE TITLE
Theme Specifications

### ISSUE THREAD

**Issue by bravo-kernel** [pester/docs#28]
# IMPORTANT

**Please do NOT provide feedback here** but instead on the theme preview PR at #29.

----

# Theme specifications

https://v2.docusaurus.io/docs/styling-layout

## General

**Most important**: similar to https://powershellgallery.com, at least applied to:

- [x] color palette
- [x] typography (UNSURE, psgallery fonts seem small, perhaps test-run) 
- [x] links
- [x] navbar (blue `#004880`, not black)
- [x] landing page hero
- [x] content navigation (left sidebar, right sidebar)

## Logo

- [x] current logo including blue background looks good on black (navbar) background
- [x] however, logo would look better in the theme without the blue background
- [x] there is no .svg logo yet
  - [ ] do we really need svg and if so, why? 
  - [x] do we have the (`.ai`?) source files and if so, can they be used to create an svg? YES: https://github.com/pester/docs/issues/28#issuecomment-583367879

## Navbar

- [x] should not change color when switching between dark mode

## Landing Page

In general, similar to https://componentkit.org/ with the following notes:

- [x] hero must have config based text and (svg?) image
- [x] sub heros must have config based text and (svg?) images
- [x] sub hero images look 'n' feel: similar to componentkit.org

**Sponsors:**

Instead of the `Also available` component on componentkit.org's landing page: 

- [x] a component to list opencollective.com sponsors

See: 

- https://docs.opencollective.com/help/collectives/data-export
- https://opencollective.com/pester/contributors.svg
- https://opencollective.com/pester/organizations.svg

## Syntax highlighting

- [x] ~might need to be updated to match new typography~ Dropped as it inherits main theme

## Footer

- [x] update `Community` row with [these socials](https://github.com/pester/Pester#got-questions)
- [x] replace `Social` row with `Sponsor` row to include links to [OpenCollective, Github, etc](https://github.com/pester/Pester#sponsored-by)

## Did we miss anything?

Not specified before but yes, we forgot about the styling of the sortable markdown tables, used a lot under the `Additional Resources` section. If possible:

- [x] make left column width max out (to prevent [weird looking tables](https://pester.dev/docs/additional-resources/misc))
- [ ] some pointers/help on making the sort arrow visible

## Bonus features (thanks @lex111)

- [x] make landing page look cool on mobile too
- [x] add sort icons to the tables

**Comment by nohwnd** [comment]
Looks good, I am trying to get the svg logo or the .ai sources.

**Comment by lex111** [comment]
I take care about this.

**Comment by bravo-kernel** [comment]
@lex111 awesome, the bounty is yours on completion. I do not want to tell you how to do your job but I personally think the preferred order for us (so we can follow and provide feedback) would be:

1. update navbar
2. clone landing page
3. update hero color

That way we have something to look at. But.. you are the expert so feel free to do any other approach.

**Comment by lex111** [comment]
@bravo-kernel could you please answer a few questions?
- Is there the Pester logo with a transparent background? On all the pictures it is with blue gradient, it would be nice to have only a logo with no background in good quality.
- Do you want to see the color navbar #004880 in two modes (light and dark)? Or is light blue (eg #0083e4) for light mode, and accordingly dark blue (#004880) for dark mode? 
- What do you mean typography? Do you want the font the same as powershellgallery.com?
- "content navigation (left sidebar, right sidebar)" - I don’t quite understand what is being discussed, could you explain this?

**Comment by bravo-kernel** [comment]
- logo: we are currently searching for the pester logo source, for now please just use the existing one
- navbar: to see what we want: go to powershellgallery.com, then inspect element of the navbar, then disable the `.navbar-inverse` class. No need to switch between dark mode, no need for gradients.

    ![image](https://user-images.githubusercontent.com/230500/73658514-ba203b00-4694-11ea-9d2b-ed0a5c544a47.png)

- typography: yes, same fonts as powershell gallery, starting with navbar and landing page (it might look bad)
- we simply mean the D2 sidebars as shown below: the will probably inherit style but were mentioned so that we do not forget about checking them

    ![image](https://user-images.githubusercontent.com/230500/73658717-21d68600-4695-11ea-96ed-0e2b1d69bd4b.png)

**Comment by lex111** [comment]
@bravo-kernel I created a PR where there is a link to the website so that you can look at the current result.

> make left column width max out (to prevent weird looking tables)
> some pointers/help on making the sort arrow visible

It seems to need clarification.

**Comment by nohwnd** [comment]
Here are .ai and .svg of the logo extracted from the pdf (all pdf are [available here](https://github.com/pester/Pester/tree/master/images)). This is supposedly very easy to do with AI, you just open the file and save it in another format. I don't own AI so I am just repeating what the guy said. Hopefully you can work with this.

In case you need the other logos converted let me know.


[pester-logo.zip](https://github.com/pester/docs/files/4170723/pester-logo.zip)

**Comment by nohwnd** [comment]
It would be nice to customize the code highlighting theme. I see that the current theme is palenight and that there are multiple others available. Do you know if there is a good website where I can try the themes online over different programming languages to see if there is any of the built-ins that I like? My main problem with the current theme is that it uses red color for some of the tokens and that is a bit jarring.

**Comment by bravo-kernel** [comment]
@nohwnd I would.. clone and run the repo locally. Then you can edit the config file to play around with themes as you see fit.

**Comment by bravo-kernel** [comment]
Closed through #29
