### ISSUE TITLE
Missing docs for FileContentMatchMultilineExactly should assertion

### ISSUE THREAD

**Issue by ArmaanMcleod** [pester/docs#294]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [issues](https://github.com/pester/docs/issues)

### Summary of the request

This assertion was added in https://github.com/pester/Pester/pull/2030, but it seems we have no documentation for it in pester docs.

### Suggested section

Assertions

**Comment by fflaten** [comment]
Thanks, good catch! It's quickly mentioned in the help for [Should](https://pester.dev/docs/commands/Should#-filecontentmatchmultilineexactly), but missing a more detailed section in the [Assertion Reference](https://pester.dev/docs/assertions/).

Would you like to contribute? 🙂

**Comment by ArmaanMcleod** [comment]
Sure will contribute to this one and create a PR. Thanks @fflaten
