### ISSUE TITLE
Installation page seems dated: doesn't cover beyond win2k16, win10, ps5

### ISSUE THREAD

**Issue by carehart** [pester/docs#298]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [issues](https://github.com/pester/docs/issues)

### Link to page

https://pester.dev/docs/introduction/installation

### What is the issue?

As elaboration on the issue title, consider this paragraph (and section titles that follow):
Compatibility
_Pester is compatible with every version of Windows that can run at least PowerShell 3. That includes: Windows 10, 8, 7, Vista, and their respective Server versions 2016, 2012 R2, 2012, 2008 R2 and 2008._

### Suggested fix?

Update page (this paragraph and sections that follow) for later versions, confirming those which are indeed supported (or if old versions of Windows or PS might no longer  be supported).

**Comment by fflaten** [comment]
Thanks for the feedback. Pester v5 currently supports Windows PowerShell 3 and later.
If you'd like to contribute, feel free to submit a PR to update the phrasing. We don't need to mention Windows versions explicitly in my opinion.

Related comment: https://github.com/pester/docs/issues/168#issuecomment-1103869040

**Comment by carehart** [comment]
But you wouldn't want me submitting that change without testing, right? I'm not committing to that or I'd have offered a pr. :-) 

I raised it here instead, hoping perhaps someone concerned about the docs being (indeed, seeming) updated might be interested to hear the observation, and might endeavor to get it updated (rallying responsible parties, etc.) 

I'm new here, first day visiting, just to give perspective.

**Comment by fflaten** [comment]
Apologies for being unclear. I sincerely appreciated the feedback and agree with your suggestion. 🙂 

I simply wanted to encourage you to submit a PR to help us fix it. This is obviously voluntary and the docs will be updated regardless.

I can confirm that Pester is compatible with all versions running Windows PowerShell 3.0 or later. No testing is required on your end if you'd you want to submit a PR.

**Comment by carehart** [comment]
OK, I gather you're saying "just go ahead and list the latest versions of Windows" (those not listed on the page already) and "we'll all assume it's good to go". I just wonder if that's wise. I hear you that Pester supports Powershell 3 and above. Does it work on a machine that runs powershell 5? or 7 (only)? If not, then such distinctions would need to be made.

And if you'd say "no, really, ANYTHING above 3 will work", I'll just say I wonder if that is (and will always be) true. In any case, I didn't want to cavalierly propose that change in versions supported, since I didn't know the answers to the above (both about how long PS3 is still supported/works, and whether Pester works ok with PS 7, for instance).

Not trying to be difficult, I promise. Just wanting to be accurate--especially if I am to be offering a change in text, especially such an important change. :-)

To repeat, my reason for raising the issue is that a newcomer to the project (like myself, because it's used by another tool I am consider) might be put off seeing such old Windows versions listed as if they were the "latest". It could discourage a prospective user of the project.

**Comment by fflaten** [comment]
PowerShell 3.0 and above works regardless of OS-version, as mentioned in [Pester's README](https://github.com/pester/Pester?tab=readme-ov-file#installation) linked in my previous comment. PowerShell itself handles most of the OS-specific behavior to give us a consistent environment.

We currently test every commit using CI against PowerShell 3.0, 4.0, 5.1 and 7 for Windows + 7 for MacOS and Ubuntu. If the OS is supported by PowerShell, it should be supported by Pester.

> I'll just say I wonder if that is (and will always be) true

Any change to current requirements will require a major release and accompanying docs updates.

I will update the instructions soon, see related PR.
