### ISSUE TITLE
Installing from sources is incorrect

### ISSUE THREAD

**Issue by nohwnd** [pester/docs#69]
Installing from sources is incorrect for v5. It states that you can just download the Pester source and run it build it requires build. We can either:
- redirect it to downloading and extracting the psgallery nuget package 
- remove that section entirely
- redirect to build instructions
- start publishing the module as zip

The first options is probably the best and I already checked that you can just Manual Download and unzip.

**Comment by fflaten** [comment]
What about changing it to "Install manually/offline" and suggest:
1. Download the module on a machine with internet using `Save-Module -Name Pester -Path C:\Temp`. It will save it in a versioned folder, ex `C:\Temp\Pester\5.0.4`
2. Copy the module-folder (`C:\Temp\Pester`) to the offline environment and place it in one of the locations defined in `$env:PSModulePath`
3. Profit

**Comment by nohwnd** [comment]
Yeah that is like the first point I have on the list, just better. :)

**Comment by simonsabin** [comment]
I agree, just point them at https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download
