### ISSUE TITLE
Implement mechanism to keep auto-generated Command Reference in-sync

### ISSUE THREAD

**Issue by bravo-kernel** [pester/docs#7]
All pages in the `Command Reference` are auto-generated using the [Alt3.Docusaurus.Powershell](https://github.com/alt3/Docusaurus.Powershell) module.

Because it uses the Get-Help documentation produced by Pester as input, it is important to implement some sort of mechanism to keep the pages in-sync with the Pester module releases. One idea talked about creating some sort of "webhook" that triggers this repo once a new Pester version is released. 

### Good to Know

Powershell used to generate the current command reference pages:

```powershell
$pesterArgs = @{
    Module = "Pester"
    DocsFolder = "docs"
    SideBar = "commands"
    Exclude = @(
      "Get-MockDynamicParameter"
      "Invoke-Mock"
      "SafeGetCommand"
      "Set-DynamicParameterVariable"
    )
    MetaDescription = 'Help page for the Powershell Pester "%1" command'
    MetaKeywords = @(
        "Powershell"
        "Pester"
        "Help"
        "Documentation"
    )
    EditUrl = 'null' # prevents `Edit this Page` button
    AppendMarkdown = "## EDIT THIS PAGE`n`nThis page was auto-generated using Pester's comment based help. To edit the content of this page, change the corresponding help in the [pester/Pester](https://github.com/pester/pester) repository. See our [contribution guide](https://github.com/pester/docs#contributing) for more information."
}

New-DocusaurusHelp @pesterArgs -Verbose
```

**Comment by bravo-kernel** [comment]
Do not feel obliged @https://github.com/glennsarti but since you were in the original discussion I thought I'd send you an update. This can be started.

**Comment by bravo-kernel** [comment]
Do not feel obliged @glennsarti but since you were in the original discussion I thought I'd send you an update. This can be started.

**Comment by glennsarti** [comment]
Thanks @bravo-kernel

**Comment by glennsarti** [comment]
Actually, that raised a question about which versions should be available. @nohwnd 

e.g. Latest 4.x and 5.x ?

**Comment by bravo-kernel** [comment]
Consensus was to start with v4 first. We will then use that version to clone a v5 later in the process.

**Comment by glennsarti** [comment]
👍 Fair enough.

**Comment by bravo-kernel** [comment]
Please be aware that you have to use the latest Pester (master) sources or the command reference will not render properly. If you have any questions please let me know.

**Comment by bravo-kernel** [comment]
@glennsarti not trying to rush you here but are you intending to implement this? If so I will assign the ticket to you (to prevent double work)

**Comment by glennsarti** [comment]
For now I can't due to workload and family stuff.  Up for grabs!

**Comment by glennsarti** [comment]
One comment.  Because the intent here is to raise commits/PRs for docs updates, there needs to be a service account/bot account within github so it can make those commits.  To the best of my knowledge there is no such account and that should be maintained, probably, by @nohwnd

**Comment by bravo-kernel** [comment]
Closing for two reasons:

1. We now have a very effictive script to actualize the docs: https://github.com/pester/docs/pull/213#issue-1291317533
2. We came to the conclusion that manual updating would be preferred

**Comment by fflaten** [comment]
> We came to the conclusion that manual updating would be preferred

👍 At least until GitHub supports repo-scoped PAT. Then we could trigger workflow on release in Pester-repo which could clone, build and generate docs.

**Comment by bravo-kernel** [comment]
Yeah that would be cool

**Comment by fflaten** [comment]
> 👍 At least until GitHub supports repo-scoped PAT. Then we could trigger workflow on release in Pester-repo which could clone, build and generate docs.

Just realized we can already solve the PAT-issue/risk with a private GitHub app in the Pester-org. It just has to be installed in the docs-repo with `actions:write`-permission, then we can use the app's private key in a simple "on published release" (exclude prerelease) workflow in Pester-repo. Example: https://github.com/fflaten/githubsandbox/runs/7171991452?check_suite_focus=true

Release tag_name (echoed in example) can be used to to either download latest version from PSGalley or clone & build if we're worried about PSGallery-delay. Will just leave the suggestion here in case this gets picked up again.

**Comment by fflaten** [comment]
Now there's also fine-grained PATs, so app no longer necessary.
See https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens/
