### ISSUE TITLE
Fix Get-Help links (in the Pester source files)

### ISSUE THREAD

**Issue by bravo-kernel** [pester/docs#8]
The auto-generated Command Reference pages use the Get-Help information produced by Pester. PlatyPS is used to make the first conversion to markdown, Alt3.Docusaurus.Powershell then enriches the markdown so it becomes compatible with Docusaurus.

The Pester sources may contain Get-Help `.LINK` sections which are converted to `External Links` as shown below:

![image](https://user-images.githubusercontent.com/230500/71326503-35ba9400-24fc-11ea-9971-2e8213958548.png)

As you can see there are currently two issues, to be fixed in the Pester source file:

1. the link to the wiki is no longer valid
2. the second link uses a wiki-specific ref that is no longer valid

Another issue that might occur in the source files is this example taken from https://github.com/pester/Pester/blob/master/Functions/Mock.ps1:

```powershell 
.LINK
Assert-MockCalled
Assert-VerifiableMock
Describe
Context
It
about_Should
about_Mocking
```

which leads to this funky link in the browser:

![image](https://user-images.githubusercontent.com/230500/71326565-dd37c680-24fc-11ea-8e28-d76f388ea050.png)

Should be fixed by creating separate `.LINK` entities as per the specification. E.g.

```powershell 
.LINK
    Assert-MockCalled

.LINK
    Assert-VerifiableMock

.LINK
    Describe

.LINK
    Context

.LINK
    It

.LINK
    about_Should

.LINK
    about_Mocking
```

**Comment by deejaygraham** [comment]
I can pick this one up.

**Comment by bravo-kernel** [comment]
Cool, that would be awesome. Please keep a couple of things in mind.

- all links in the source should probably be a direct link to the corresponding pester.dev website (e.g. replacce `It` with the full link (or the website links will not work)
- we should probably make this a co-op. You make the changes in Pester repository, I use your Pester PR branch to generate a PR in this repository with the auto-generated command reference here. 

Does that sound ok to you?

**Comment by deejaygraham** [comment]
Yes, think so.

**Comment by deejaygraham** [comment]
Broke the blocks of links into separate chunks yesterday but before I go any further, I want to check about the actual link text. I get that some are using the old url and the wrong page name that can be fixed. I am more wondering about whether each command should have an online link to the docs . For example I think this is correct (with comments afterwards):

Context

...

.LINK
https://pester.dev/docs/commands/Context (change url)

.LINK
Describe (related command, leave as is ?)

.LINK
about_Should (related command, leave as is ?)

**Comment by bravo-kernel** [comment]
I guess @nohwnd should check your Pester PR, see what he thinks.

**Comment by bravo-kernel** [comment]
If you are for example suggesting we should leave ‘about_Should’ exactly that text then I wonder what happens inside Docusaurus. Does it produce a valid URL by itself? If not, changing it to full url should be the best solution IMO but that’s personal. I prefer to see full links when running Get-Help but... perhaps other systems/tools expect this format.

Apologies for the long text, was a bit of a long day

**Comment by deejaygraham** [comment]
No, no problem. I'll make a PR as it is with fixed links etc. but leave the rest alone for now and we can see what opinions come out.

**Comment by bravo-kernel** [comment]
Aha, I think I understand now. I will generate a PR here using your Pester PR somewhere this Friday or weekend. That way we can reason about/view the outcome. Thanks again!

**Comment by deejaygraham** [comment]
https://github.com/pester/Pester/pull/1432 

Added a note about what the correct format is for all .LINK entries.
