### ISSUE TITLE
Updating help automatically from latest release

### ISSUE THREAD

**Issue by nohwnd** [pester/docs#84]
## File changes

The [generate-command-reference.ps1](https://github.com/pester/docs/blob/master/generate-command-reference.ps1) script:
  -  only generates the ` .mdx` files and the `docusaurus.sidebar.js` file found in [this docs\command directory](https://github.com/pester/docs/tree/master/docs/commands)
 - then replaces the existing content of above folder with the newly generated mdx files
 - only mdx file changes will appear in the PR

## The process

We already have a working process, it just needs some fine tuning IMO.

1. Do not move generate script out of the pester/docs repo
2. Update the generate script so it no longer uses a fixed Pester version but either:
   - uses latest Pester version (by default)
   - uses a specified Pester version if parameter is given (e.g. `-PesterVersion`)
3. Use that updated script to implement CI/CD

## CI/CD

A solution was discussed earlier, something like:

1. pester/pester repo creates a new release
2. pester/pester release triggers a github action in the pester/docs repo
3. that pester/docs action uses the generate script to:
    - regenerate the mdx files using LATEST pester version
    - create a PR with the mdx file changes

This way everything stays as it is now with wesbite-previews etc. and.. no need to move pester-docs-related logic into the pester/pester repo.

Does that make sense?

_Originally posted by @bravo-kernel in https://github.com/pester/Pester/issues/1798#issuecomment-737134366_

**Comment by glennsarti** [comment]
PR for release process on Pester is at https://github.com/pester/Pester/pull/1818

**Comment by glennsarti** [comment]
Chose not to use GH releases as there doesn't seem to be a direct correlation between a GH release and a package being available on PS Gallery.  Unfortunately the release process for Pester is not documented so I had to "reverse engineer" from code comments and commit messages.

**Comment by bravo-kernel** [comment]
This looks great @glennsarti. Thanks for making this happen ❤️

**Comment by bravo-kernel** [comment]
**ps:** you are correct, there is no direct correlation between the PSGallery and Github Releases, they are just created one after the other. IMO Pester should ideally use an automated ci/cd pipeline to publish to them both, with the docs trigger rounding things up.

I'm doing something similar with auto-publishing to both here:

- https://dev.azure.com/alt3bv/Docusaurus.Powershell/_build/results?buildId=707&view=results
- https://github.com/alt3/Docusaurus.Powershell/tree/master/.azure-templates/jobs/cd

**Comment by nohwnd** [comment]
There are 2 problems automating this. 

1) I write the release docs manually, not just generate them so publishing the file manually is simpler than copying the content somewhere and then have it automatically published to github. 

2) I code sign the package, so my certificate needs to be accessible to the build server, and just the build server and no-one else to keep it safe. This means I would have to deploy a separate vm to do just the publishing, which is not difficult, but is more difficult than just doing it on my system, especially because I am already doing tweaks to the code before publishing anyway.

That said I think I almost always publish in this order: Make Github Release draft, publish to PSGallery, Publish release on Github. So triggering the rebuild of docs on new release in Pester repo should be valid. But I am also okay with the way it's done in the release script.

I should publish updated Pester package this week so we will see how this change works. Thanks guys!

**Comment by bravo-kernel** [comment]
Given the small amount of Pester releases it might not be a bad idea to keep this as a manual step for now.

Simply keep publishing Pester like you always do. All done, simply trigger this action manually.

**Comment by fflaten** [comment]
> I should publish updated Pester package this week so we will see how this change works. Thanks guys!

Missing the 5.2.x refresh. Got time to trigger it?

**Comment by nohwnd** [comment]
@fflaten I did it (before you asked 🤪) https://github.com/pester/docs/pull/112

**Comment by nohwnd** [comment]
Undecided on the automation from Pester side. Thanks for putting the work in, but it's making my release a bit more complicated. I think I will just get into the habit of triggering it manually.

**Comment by bravo-kernel** [comment]
Closing as motivated here https://github.com/pester/docs/issues/7#issuecomment-1172872045
