### ISSUE TITLE
Legacy interface is wrong

### ISSUE THREAD

**Issue by benja83** [pester/docs#97]
Some of the mapping value between legacy and v5 regarding the code coverage documentation are wrong in the following link https://github.com/pester/Pester#legacy-interface.

| Parameter                                             | Current value for Configuration Object Property            | Real value
| -------------------------------          | ------------------------------------------------------ |----------------
| CodeCoverage                                    | CodeCoverage.Path                                                             | CodeCoverage.Path    
| CodeCoverageOutputFile                  | CodeCoverage.CodeCoverageOutputFile                          |  CodeCoverage.OutputPath | 
| CodeCoverageOutputFileEncoding  | CodeCoverage.CodeCoverageOutputFileEncoding          | CodeCoverage.OutputEncoding|
| CodeCoverageOutputFileFormat      | CodeCoverage.CodeCoverageOutputFileFormat              | CodeCoverage.OutputFormat|

Should I create a PR in this repo or in the Pester one?

**Comment by bravo-kernel** [comment]
This should be changed in the readme of the pester repo.

That full readme will/should be ported to the docs website but activity has been slow on that area.

**Comment by nohwnd** [comment]
> That full readme will/should be ported to the docs website but activity has been slow on that area.

Working on that in #98
